spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/DIARY
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
       show_sql: true
      format_sql: true
  session:
    store-type: jdbc
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
      initialize-schema: embedded
      table-name: SPRING_SESSION


  profiles:
    include: oauth

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    session:
      timeout: