spring:
  security:
    oauth2:
      client:
        registration:
          # 네이버는 Spring Security를 공식 지원하지 않기 때문에 CommonOAuth2Provider 에서 해주는 값들을 수동으로 입력한다.
          naver:
            client-id: KpgcYfVgsCWMXsXWCRZZ
            client-secret: joivb1qtwm
            # yaml 에서는 / (슬러시)를 그대로 쓰면 파싱 에러가 난다. 따옴표나 작은 따옴표로 감싸야함
            # redirect-url 이 아니고 redirect-uri
            redirect-uri: http://localhost:8080/login/oauth2/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # 네이버에서 json 반환, json 내 respose 키 안에 name, email 있음
            user-name-attribute: response
